### ISSUE TITLE
Using the library causes a java.lang.NoClassDefFoundError exception

### ISSUE THREAD

**Issue by iiordanov** [connectbot/trilead-ssh2#31]
The library was built with the provided gradlew script on a system running java 1.8.

It looks like the library does not include an implementation of Daniel Bernstein's Curve22519 key. Am I doing something wrong or is it a bug?

 
`
01-18 00:32:46.212 12320 12353 E AndroidRuntime: FATAL EXCEPTION: Thread-5
01-18 00:32:46.212 12320 12353 E AndroidRuntime: Process: com.iiordanov.bVNC, PID: 12320
01-18 00:32:46.212 12320 12353 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ldjb/Curve25519;
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at com.trilead.ssh2.crypto.dh.Curve25519Exchange.init(Curve25519Exchange.java:42)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:554)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:608)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:302)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "djb.Curve25519" on path: DexPathList[[zip file "/data/app/com.iiordanov.bVNC-1/base.apk"],nativeLibraryDirectories=[/data/app/com.iiordanov.bVNC-1/lib/arm, /system/fake-libs, /data/app/com.iiordanov.bVNC-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-18 00:32:46.212 12320 12353 E AndroidRuntime: 	... 5 more
`

Thanks for providing this library!
iordan

PS. I had to add some options to gradle on a system with java 1.8. I can provide a pull request if you prefer, please let me know!
`
diff --git a/sshlib/build.gradle b/sshlib/build.gradle
index 1728a8d..e61d66a 100644
--- a/sshlib/build.gradle
+++ b/sshlib/build.gradle
@@ -6,6 +6,10 @@ plugins {
 apply plugin: 'java'
 apply from: "${rootDir}/publish.gradle"
 
+targetCompatibility = "1.7"
+
+sourceCompatibility = "1.7"
+
 dependencies {
     compile fileTree(dir: 'libs', include: ['*.jar'])
     compile 'com.jcraft:jzlib:1.1.3'
`

**Comment by iiordanov** [comment]
Turns out I needed a few additional libraries, and in case it helps somebody, they were:

`
bcpkix-jdk15on-1.48.jar
bcprov-jdk15on-1.48.jar
ecc-25519-java-1.0.3.jar
eddsa-0.1.0.jar
`
The targetCompatibility and sourceCompatibility flag question still stands.
