### ISSUE TITLE
When establishing a connection to a machine with ed25519 host keys, sshlib crashes with a NullPointerException

### ISSUE THREAD

**Issue by iiordanov** [connectbot/trilead-ssh2#43]
The stacktrace:

```04-15 18:14:04.201 22764 22822 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'net.i2p.crypto.eddsa.math.Curve net.i2p.crypto.eddsa.spec.EdDSAParameterSpec.getCurve()' on a null object reference
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at net.i2p.crypto.eddsa.spec.EdDSAPublicKeySpec.<init>(EdDSAPublicKeySpec.java:20)
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at com.trilead.ssh2.signature.Ed25519Verify.decodeSSHEd25519PublicKey(Ed25519Verify.java:79)
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at com.trilead.ssh2.transport.KexManager.verifySignature(KexManager.java:433)
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:756)
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:617)
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:311)
04-15 18:14:04.201 22764 22822 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

Removing the ed25519 host key or reverting to commit e3fce7c173e3a9deb44251ffe21224c6aa29974b circumvents the issue.

**Comment by kruton** [comment]
Are you sure that's the right commit to revert? That particular commit doesn't seem relevant.

**Comment by iiordanov** [comment]
I didn't mean reverting that commit, I meant reverting to that commit (i.e. backing out all subsequent commits).

**Comment by kruton** [comment]
Hmm, that line number doesn't match up with 0.2.0 of the eddsa library, but it matches with [0.1.0](https://github.com/str4d/ed25519-java/blob/v0.1.0/src/net/i2p/crypto/eddsa/spec/EdDSAPublicKeySpec.java). Could you try refreshing your gradle build? It looks like it has stale dependencies.

**Comment by iiordanov** [comment]
You are right! Made sure to build with 0.2.0, and things are working now. Thanks!
